[programs.localnet]
myepicproject = "6ujPm31Hz1ik1FBwyrfAmH4WEgbMr3SHpnXqNAWXaSBm"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/peter/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js" 
